#!/usr/bin/env bash
# Shows information about subdomains.

#Function to retrieve and display information about a subdomain.
domain_information() {
    local domain="$1"
    local subdomain="$2"
    local line
    # Performs DNS lookup for the subdomain under the specified domain.
    line=$(dig "$2"."$1" | grep -A1 '/ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    # Extracting information
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3 "}'
    #echo "$2 $line" | awk '{printf "The subdomain %s is a %s record and points to %s\n", $1, $2, $3}'
}

if [ "$#" == 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" == 2 ]; then
    domain_information "$1" "$2"
fi
