#!/usr/bin/env bash
# This is a comment line
# The first line tells the shell which interpreter to use
# The next line prints a message to the user
while IFS= read -r contents
do
	echo "$content" | cut -f 1,3,6 -d ':'
	# The next line uses the cat command to display the file content
done < "/etc/passwd"
