#!/usr/bin/env bash
# Read /etc/passwd file line by line using while loop + IFS
while IFS=: read -r USER_NAME PASSWORD USER_ID GROUP_ID USER_ID_INFO HOME_DIRECTORY COMMAND
do
  # Display the formatted output
  echo "The user $USER_NAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND."
  echo "$USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
  echo # Add a blank line for readability
done < /etc/passwd # Redirect the file to the loop
