#!/usr/bin/env bash
# A bash script that displays "Best School" 10 times using a while
#   loop on the 9th iteration, displays "Hi" before "Best School".

counter=0

while [ $counter -lt 10 ]
do
  if [ $counter -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( counter++ ))
done

exit 0
