#!/usr/bin/env bash
# SSH client config

Include /etc/ssh/ssh_config.d/*.conf

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
